### ISSUE TITLE
No materials data is installed

### ISSUE THREAD

**Issue by rprr** [quartiq/rayopt#22]
I used the conda method to install. However, I cannot run any of the examples as the material data does not seem to be installed. Or is it a path issue?

**Comment by jordens** [comment]
Does the tutorial run?
The zemax and Oslo data are not distributed. You have to import them yourself. The refractiveibdex.info data is included.

**Comment by rprr** [comment]
Thanks. The tutorial run all the way except the very last step. I will figure out how to import the zemax and Oslo data. 

Please forgive my newbieness. I am trying to figure out how all of this works. I have a fairly simple multiple mirror system (all planar). Just trying to simulate this. Most of the examples seem fairly complex with lenses.

**Comment by jordens** [comment]
Go ahead and ask your questions  that's what this is for. If your system is all mirrors you don't even need any materials database.
