### ISSUE TITLE
Question: is there a way to scale a design?

### ISSUE THREAD

**Issue by dibyendumajumdar** [quartiq/rayopt#24]
Hi,

Sometimes in patent literature the data is presented in a different scale than the actual values.
For instance the patent JP2019090947A describes the Z Nikkor 35mm f1.8 but presents the data scaled so that it appears to be a miniature lens.  i would like to normalize so that different designs are comparable.

Thank you

Regards

**Comment by dibyendumajumdar** [comment]
Hi,

I found a rescale() method that presumably does this?
However, when I compare the spot diagrams for rescaled versions to one I manually rescaled, they do not appear the same. Basically after rescaling the spot diagrams look the same as before the rescaling.

Example:

Original:
https://github.com/cameragossip/cameragossip.github.io/blob/master/lensdesigns/Nikkor-Z-35mm-f1.8-JP2019090947A.ipynb

Manual rescaling:
https://github.com/cameragossip/cameragossip.github.io/blob/master/lensdesigns/Nikkor-Z-35mm-f1.8-JP2019090947A-scaled.ipynb

If I used the rescale() method the spot diagrams do not change from the 1st example above.

**Comment by jordens** [comment]
The `System()` has a `scale` attribute which you can simply set. It's in SI units and defaults to mm (`1e-3`). distances radii, aspheric coefficnets etc are all in those units. But not the wavelengths. `rescale()` just changes scale units, nothing else. The system will behave exactly the same, the Airy radius for example will remain the same in SI units, but changes in system units.

**Comment by dibyendumajumdar** [comment]
Okay thank you.
