### ISSUE TITLE
Question: how to do close focus scenario

### ISSUE THREAD

**Issue by dibyendumajumdar** [quartiq/rayopt#25]
Hi @jordens ,
I am trying to add a close focus scenario for the Z Noct Nikkor 58mm f0.98 but I am getting an error.
I am guessing that I need to tell rayopt that the object is not an infinity but I don't know how to do this.

https://nbviewer.jupyter.org/github/cameragossip/cameragossip.github.io/blob/master/lensdesigns/Nikkor-Z-Noct-58mm-f0.95.ipynb

Thanks and Regards
Dibyendu

**Comment by jordens** [comment]
Look at the other examples. The lithograph, the catadioptric etc
