### ISSUE TITLE
Formula for aspherical surfaces

### ISSUE THREAD

**Issue by dibyendumajumdar** [quartiq/rayopt#27]
Hi,
I believe the aspheric surface is computed in Spheroid.surface_sag() method?
I would like to know the formula used. In particular:

```
r2 = np.einsum("...i,...i", xy, xy)
if self.curvature:
     c, k = self.curvature, self.conic
      e -= c*r2/(1 + np.sqrt(1 - (1 + k)*c**2*r2))
```

In this what does r2 represent? Is it the height squared?
Is c a reciprocal of the input radius?

In the case of the 58mm Noct that I have looking at the patent specifies this formula:

```
x = (h**2 / r) / [1+ {1− (1 + κ) · (h / r)**2 } 1/2 ]
+ A4h**4 + A6h**6 + A8h**8 + A10h**10 + A12h**12 + A14h**14
Here, h is the height in the direction perpendicular to the optical axis, 
x is the distance along the optical axis direction from the tangent 
plane of the apex of the aspheric surface at the height h to the 
aspheric surface, 
and κ is the conic constant. 
```
Comparing the two, I think that if h**2 = r2, and c = 1/r then the two formulas match?

**Comment by jordens** [comment]
Yes to all
