### ISSUE TITLE
Question: Which value should match Fno on a patent 

### ISSUE THREAD

**Issue by dibyendumajumdar** [quartiq/rayopt#28]
We get output such as:

front, back f number: [1.45   1.2221]
front, back working f number: [   inf 1.5338]

Which of these values should match the Fno conventionally specified in patent literature?

Thanks and Regards

**Comment by jordens** [comment]
Depends very much on the patent. For typical camera lenses it's the front f number.
These questions of yours are are not issues. You could answer them yourself by reading the books I cited for you or the code. But the answers contain generally useful information. Could you add them to the documentation?

**Comment by dibyendumajumdar** [comment]
> These questions of yours are are not issues. 

Indeed that is why I mark them as questions. It is common practice to raise questions as issues so that other people can benefit from the answers.

> You could answer them yourself by reading the books I cited for you or the code. 

Yes, at some point I will try to dig deeper into the code and I just bought the Handbook - so thank you for the references.

I am still trying to decide whether there is an issue or not. For instance the Fno obtained by another software matches the patent - in case of the Noct - but using rayopt with same spec it doesn't.

> But the answers contain generally useful information. Could you add them to the documentation?

Yes I am hoping to add docs to the project. I don't know if it is better to follow Python style docs in the code itself or create separate docs. I hope you will accept patches if I submit docs.

Thanks for answering the stupid questions. I get that anyone familiar with Zemax or OSLO or skilled in the field would not be asking such questions.

**Comment by jordens** [comment]
Sorry if I came across a bit rash. I appreciate that you are interested and playing with it.

The f number for a photographic lens is only determined by the entrance pupil size at infinite conjugate (it is focal length/entrance pupil size), which again is determined by the stop size. What you'd do is adjust the aperture stop size to match the "f number". Alternatively you'd specify a `FnoPupil` for the object and don't let the paraxial properties be determined by stop size. I haven't extensively tested it and there may be bugs in `FnoPupil`.
