### ISSUE TITLE
Question: Impact of cover glass in front of a digital sensor

### ISSUE THREAD

**Issue by dibyendumajumdar** [quartiq/rayopt#29]
I mentioned before that with some patents I am not getting a good match on the f number. I think that pattern I am seeing is that when a design has a cover glass in front of the image plane (in digital cameras newer designs take into account the impact of the cover glass) then I see the discrepancy. So presumably rayopt is considering the cover glass as just a regular optical element - and I guess that this impacting the result somehow? Any thoughts?

I think that the performance figures are adversely affected when the F no doesn't get close.

I have more examples you can see here : https://nbviewer.jupyter.org/github/cameragossip/cameragossip.github.io/tree/master/lensdesigns/

**Comment by jordens** [comment]
The chip cover glass doesn't matter for f number.
For learning i'd recommend working with simple designs instead of adding more and more complex designs.
